---
- hosts: all
  become: yes
  tasks:
  - name: install wget
    apt:
     name: wget
     status: present
     when: ansible_os_family== "Debian"
  - name: install git
    yum:
     name: git
     status: present
     when: ansible_os_family== "Redhat"