---
- hosts: 172.31.16.63
  become: yes
  tasks:
  - name: install webserver
    yum:
      name: apache2
      state: present

  - name: start webserver
    service:
      name: apache2
      state: started


    